import React, { useEffect, useState } from 'react';
import { streamUrl } from './api';

// Live metrics via SSE. EVERY user/traffic number here is SIMULATED (driven by the
// built-in load generator); the panel says so explicitly - we never claim real users.
export default function MetricsPanel() {
  const [m, setM] = useState(null);
  const [connected, setConnected] = useState(false);

  useEffect(() => {
    const es = new EventSource(streamUrl('/metrics'));
    es.addEventListener('metrics', ev => {
      setConnected(true);
      try { setM(JSON.parse(ev.data)); } catch { /* ignore */ }
    });
    es.onerror = () => setConnected(false);
    return () => es.close();
  }, []);

  const stat = (label, value, cls = '') => (
    <div className={`metric ${cls}`}>
      <div className="metric-value">{value}</div>
      <div className="metric-label">{label}</div>
    </div>
  );

  return (
    <section className="panel metrics-panel">
      <div className="panel-head">
        <h3>Live metrics <span className={`dot ${connected ? 'dot-on' : ''}`} /></h3>
        <span className="sim-badge" title="All traffic and user figures are generated by the built-in load generator.">
          SIMULATED
        </span>
      </div>
      <div className="metrics-grid">
        {stat('simulated users', m ? m.simulated_users : '--')}
        {stat('requests / min', m ? m.requests_per_min : '--')}
        {stat('p95 latency', m ? `${m.p95_latency_ms} ms` : '--')}
        {stat('heals applied', m ? m.heals_applied : '--', m && m.heals_applied > 0 ? 'metric-heal' : '')}
        {stat('drift caught', m ? m.drift_caught : '--', m && m.drift_caught > 0 ? 'metric-drift' : '')}
        {stat('error rate', m ? `${m.error_rate_pct}%` : '--', m && m.error_rate_pct > 1 ? 'metric-bad' : '')}
      </div>
    </section>
  );
}
